---
- name: Bootstrap server with Docker + Traefik + Cloudflare Tunnel
  hosts: bare_metal
  become: true
  
  pre_tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      
    - name: Upgrade all packages to latest version
      apt:
        upgrade: full
        update_cache: yes
        autoremove: yes
        
    - name: Gather service facts
      service_facts:
    
    - name: Check for required variables
      fail:
        msg: "Please configure at least one domain in group_vars/all.yml"
      when: domains is not defined or domains | length == 0 or domains[0] == ""
    
    - name: Check for Tunnel ID
      pause:
        prompt: "Enter your Cloudflare Tunnel UUID"
      register: tunnel_id_prompt
      when: tunnel_id is not defined or tunnel_id == ""
    
    - name: Set Tunnel ID
      set_fact:
        tunnel_id: "{{ tunnel_id_prompt.user_input }}"
      when: (tunnel_id is not defined or tunnel_id == "") and tunnel_id_prompt.user_input is defined
    
    - name: Set default SSH port if not defined
      set_fact:
        ssh_port: "22"
      when: ssh_port is not defined
  
  roles:
    - role: firewall
      tags: ['firewall']
    - role: docker
      tags: ['docker']
    - role: traefik
      tags: ['traefik']
    - role: cloudflared
      tags: ['cloudflared']