---
# Handlers for firewall role

- name: Promote v4 rules
  shell: |
    mv /etc/iptables/rules.v4.tmp /etc/iptables/rules.v4
    chmod 600 /etc/iptables/rules.v4
  become: true
  notify: Restart Docker service

- name: Promote v6 rules
  shell: |
    mv /etc/iptables/rules.v6.tmp /etc/iptables/rules.v6
    chmod 600 /etc/iptables/rules.v6
  become: true
  notify: Restart Docker service

# If docker service is installed, we will restart it when the rules are promoted.
# If it is not installed, the docker role will install it and start it later.
- name: Restart Docker service
  systemd:
    name: docker
    state: restarted
  become: true
  when:
    - ansible_facts.services is defined
    - "'docker.service' in ansible_facts.services"
